2023-10-11 12:20:41,264 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2023-10-11 12:20:41,270 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'describe']
2023-10-11 12:20:41,270 DEBUG    root            Running [gcloud.projects.describe] with arguments: [--account: "s-nakaue@glad-cube.com", --configuration: "s-nakaue", --format: "value(name)", PROJECT_ID_OR_NUMBER: "fastest-prod"]
2023-10-11 12:20:41,303 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-10-11 12:20:41,305 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c238e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:41,305 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/fastest-prod?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c238e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:42,926 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-10-11 12:20:42,929 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c23880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:42,929 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/fastest-prod?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c23880>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:47,003 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-10-11 12:20:47,004 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c23970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:47,004 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/fastest-prod?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c23970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:56,932 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-10-11 12:20:56,935 DEBUG    root            Caught socket error, retrying: HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c239a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:20:56,935 DEBUG    root            Retrying request to url https://cloudresourcemanager.googleapis.com/v1/projects/fastest-prod?alt=json after exception HTTPSConnectionPool(host='cloudresourcemanager.googleapis.com', port=443): Max retries exceeded with url: /v1/projects/fastest-prod?alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x106c239a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-10-11 12:21:12,641 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2023-10-11 12:21:13,405 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/projects/fastest-prod?alt=json HTTP/1.1" 200 None
2023-10-11 12:21:13,410 INFO     root            Display format: "default value(name)"
2023-10-11 12:21:13,411 INFO     ___FILE_ONLY___ fastest-prod

2023-10-11 12:21:13,430 DEBUG    root            Metrics reporting process started...
